credentials:
  usernames:
    monheart:
      email: ism.bolat@hotmail.com
      logged_in: False # Will be managed automatically
      name: ismail bolat
      password: x500 # Will be hashed automatically
    ismail:
      email: ism.bolat@hotmail.com
      logged_in: False # Will be managed automatically
      name: Hasan Kara
      password: makro500 # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - ism.bolat@hotmail.com

